vim.opt.number = true
vim.opt.mouse = 'a'
vim.opt.expandtab = true
vim.opt.shiftwidth = 3
vim.opt.softtabstop = 3
vim.opt.termguicolors = true
vim.opt.showmode = false
vim.opt.foldmethod = 'expr'
vim.opt.foldexpr= 'nvim_treesitter#foldexpr()'
vim.g.mapleader = ','
vim.o.guifont = 'mononoki NF'
vim.o.laststatus = 3
