vim.opt.number = true
vim.opt.mouse = 'a'
vim.opt.expandtab = true
vim.opt.shiftwidth = 3
vim.opt.softtabstop = 3
vim.opt.termguicolors = true
vim.opt.showmode = false
vim.opt.foldmethod = 'indent'
vim.g.mapleader = ','
vim.o.guifont = 'mononoki NF'
vim.opt_local.formatoptions = {}
