{ pkgs, ... }: {
  imports = [
    ../home-manager/common
    ../home-manager/clipman.nix
    ../home-manager/direnv.nix
    ../home-manager/dunst.nix
    ../home-manager/gammastep.nix
    ../home-manager/gnome-keyring.nix
    ../home-manager/gtk.nix
    ../home-manager/mimeApps.nix
    ../home-manager/sway-audio-idle-inhibit.nix
    ../home-manager/sway.nix
    ../home-manager/swayidle.nix
    ../home-manager/swaylock.nix
    ../home-manager/waybar.nix
    ../home-manager/wezterm.nix
    ../home-manager/wob.nix
    ../home-manager/wofi.nix
    ./options/colors.nix
    ./options/swayDisplayReloadFix.nix
    ./options/wofi-logout.nix
  ];
  home.packages = with pkgs; [
    anki
    bluez
    brave
    brillo
    cargo
    capitaine-cursors
    dracula-theme
    firefox
    gcc
    glib
    grim
    gnome.adwaita-icon-theme
    gnome.seahorse
    htop
    nixos-artwork.wallpapers.nineish-dark-gray
    python3Full
    playerctl
    pavucontrol
    pamixer
    rustc
    swappy
    slurp
    thunderbird
    virt-manager
    wl-clipboard
    wayland
    xwayland
  ];
}
